config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :airports
  resources :passenger_details
  resources :bookings
  resources :flight_schedules
  resources :flights
  get "/cancle_booking/:id" => "bookings#cancle_booking", :via => :post, :as => :cancle_booking

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/passenger_detail.rb
class PassengerDetail < ApplicationRecord
	belongs_to :booking
	validate do |passenger_detail|
		if passenger_detail.date_of_birth.present? && passenger_detail.date_of_birth > (Date.today - 18.years)
	    	errors.add(:expiration_date, "Aage should be greter then 18 years")
	    end
	end
end

app/controllers/passenger_details_controller.rb
class PassengerDetailsController < ApplicationController
  before_action :set_passenger_detail, only: %i[ show edit update destroy ]

  # GET /passenger_details or /passenger_details.json
  def index
    @passenger_details = PassengerDetail.all
  end

  # GET /passenger_details/1 or /passenger_details/1.json
  def show
  end

  # GET /passenger_details/new
  def new
    @passenger_detail = PassengerDetail.new
  end

  # GET /passenger_details/1/edit
  def edit
  end

  # POST /passenger_details or /passenger_details.json
  def create
    @passenger_detail = PassengerDetail.new(passenger_detail_params)

    respond_to do |format|
      if @passenger_detail.save
        format.html { redirect_to passenger_detail_url(@passenger_detail), notice: "Passenger detail was successfully created." }
        format.json { render :show, status: :created, location: @passenger_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @passenger_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passenger_details/1 or /passenger_details/1.json
  def update
    respond_to do |format|
      if @passenger_detail.update(passenger_detail_params)
        format.html { redirect_to passenger_detail_url(@passenger_detail), notice: "Passenger detail was successfully updated." }
        format.json { render :show, status: :ok, location: @passenger_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @passenger_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passenger_details/1 or /passenger_details/1.json
  def destroy
    @passenger_detail.destroy

    respond_to do |format|
      format.html { redirect_to passenger_details_url, notice: "Passenger detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger_detail
      @passenger_detail = PassengerDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_detail_params
      params.require(:passenger_detail).permit(:booking_id, :first_name, :last_name, :gender, :date_of_birth)
    end
end

app/helpers/passenger_details_helper.rb
module PassengerDetailsHelper
end

app/views/passenger_details/_form.html.erb
<%= form_with(model: passenger_detail, local: true) do |form| %>
  <% if passenger_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger_detail.errors.count, "error") %> prohibited this passenger_detail from being saved:</h2>

      <ul>
        <% passenger_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :booking_id %>
    <%= form.number_field :booking_id %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passenger_details/edit.html.erb
<h1>Editing Passenger Detail</h1>

<%= render 'form', passenger_detail: @passenger_detail %>

<%= link_to 'Show', @passenger_detail %> |
<%= link_to 'Back', passenger_details_path %>

app/views/passenger_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passenger Details</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Booking</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passenger_details.each do |passenger_detail| %>
      <tr>
        <td><%= passenger_detail.booking_id %></td>
        <td><%= passenger_detail.first_name %></td>
        <td><%= passenger_detail.last_name %></td>
        <td><%= passenger_detail.gender %></td>
        <td><%= passenger_detail.date_of_birth %></td>
        <td><%= link_to 'Show', passenger_detail %></td>
        <td><%= link_to 'Edit', edit_passenger_detail_path(passenger_detail) %></td>
        <td><%= link_to 'Destroy', passenger_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger Detail', new_passenger_detail_path %>

app/views/passenger_details/new.html.erb
<h1>New Passenger Detail</h1>

<%= render 'form', passenger_detail: @passenger_detail %>

<%= link_to 'Back', passenger_details_path %>

app/views/passenger_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booking:</strong>
  <%= @passenger_detail.booking_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @passenger_detail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @passenger_detail.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @passenger_detail.gender %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @passenger_detail.date_of_birth %>
</p>

<%= link_to 'Edit', edit_passenger_detail_path(@passenger_detail) %> |
<%= link_to 'Back', passenger_details_path %>