config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :airports
  resources :passenger_details
  resources :bookings
  resources :flight_schedules
  resources :flights
  get "/cancle_booking/:id" => "bookings#cancle_booking", :via => :post, :as => :cancle_booking

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight_schedule.rb
class FlightSchedule < ApplicationRecord
	belongs_to :flight
	has_many :bookings, dependent: :destroy
	belongs_to :departure_airport, :class_name => "Airport"
	belongs_to :destination_airport, :class_name => "Airport"
	scope :search_by_params, -> (params) { where('departure_airport_id = ? and destination_airport_id = ? and date > ? and date < ?', params[:departure_airport_id], params[:destination_airport_id], params[:departure_date].to_date || Date.today, (params[:departure_date].to_date || Date.today) + 1.day) }

end

app/controllers/flight_schedules_controller.rb
class FlightSchedulesController < ApplicationController
  before_action :set_flight_schedule, only: %i[ show edit update destroy ]

  # GET /flight_schedules or /flight_schedules.json
  def index
    if params[:departure_airport_id].present? && params[:destination_airport_id].present?
      @flight_schedules = FlightSchedule.search_by_params(params).order(:date)
    else
      @flight_schedules = FlightSchedule.all
    end
  end

  # GET /flight_schedules/1 or /flight_schedules/1.json
  def show
    confirmed_booking_ids = @flight_schedule.bookings.confirmed?.pluck(:id)
    @total_men_passenger = PassengerDetail.where(gender: "Male", booking_id: confirmed_booking_ids).count
    @total_women_passenger = PassengerDetail.where(gender: "Female", booking_id: confirmed_booking_ids).count
  end

  # GET /flight_schedules/new
  def new
    @flight_schedule = FlightSchedule.new
  end

  # GET /flight_schedules/1/edit
  def edit
  end

  # POST /flight_schedules or /flight_schedules.json
  def create
    @flight_schedule = FlightSchedule.new(flight_schedule_params)

    respond_to do |format|
      if @flight_schedule.save
        format.html { redirect_to flight_schedule_url(@flight_schedule), notice: "Flight schedule was successfully created." }
        format.json { render :show, status: :created, location: @flight_schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flight_schedules/1 or /flight_schedules/1.json
  def update
    respond_to do |format|
      if @flight_schedule.update(flight_schedule_params)
        format.html { redirect_to flight_schedule_url(@flight_schedule), notice: "Flight schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @flight_schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flight_schedules/1 or /flight_schedules/1.json
  def destroy
    @flight_schedule.destroy

    respond_to do |format|
      format.html { redirect_to flight_schedules_url, notice: "Flight schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight_schedule
      @flight_schedule = FlightSchedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_schedule_params
      params.require(:flight_schedule).permit(:flight_id, :departure_airport_id, :destination_airport_id, :date, :price)
    end
end

app/helpers/flight_schedules_helper.rb
module FlightSchedulesHelper
end

app/views/flight_schedules/_form.html.erb
<%= form_with(model: flight_schedule, local: true) do |form| %>
  <% if flight_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight_schedule.errors.count, "error") %> prohibited this flight_schedule from being saved:</h2>

      <ul>
        <% flight_schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.number_field :flight_id %>
  </div>

  <div class="field">
    <%= form.label :departure_airport_id %>
    <%= form.number_field :departure_airport_id %>
  </div>

  <div class="field">
    <%= form.label :destination_airport_id %>
    <%= form.number_field :destination_airport_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flight_schedules/edit.html.erb
<h1>Editing Flight Schedule</h1>

<%= render 'form', flight_schedule: @flight_schedule %>

<%= link_to 'Show', @flight_schedule %> |
<%= link_to 'Back', flight_schedules_path %>

app/views/flight_schedules/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(url: "flight_schedules", html: {class: "d-flex"}, method: :get) do |f| %>
  <%= f.collection_select :departure_airport_id, Airport.all, :id, :city, options ={prompt: "Please Select Departure", selected: params[:departure_airport_id]}, {class: "form-select form-select-lg mb-3"} %>
  <%= f.collection_select :destination_airport_id, Airport.all, :id, :city, options ={prompt: "Please Select Destination", selected: params[:destination_airport_id]}, {class: "form-select form-select-lg mb-3"} %>
  <%= f.text_field :departure_date, class: "input-group-text mb-3", placeholder: "Enter Departure Date dd/mm/yyy", value: params[:departure_date] %>
  <%= f.submit 'Search', class: "btn btn-outline-success mb-3"%>
<% end %>

<h1>Flight Schedules</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Flight</th>
      <th>Departure airport</th>
      <th>Destination airport</th>
      <th>Date</th>
      <th>Price</th>
      <th colspan="2"></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_schedules.each do |flight_schedule| %>
      <tr>
        <td><%= flight_schedule.flight.name %> - <%= flight_schedule.flight.code %></td>
        <td><%= flight_schedule.departure_airport.city %></td>
        <td><%= flight_schedule.destination_airport.city %></td>
        <td><%= flight_schedule.date %></td>
        <td><%= flight_schedule.price %></td>
        <td><%= link_to 'Book', new_booking_path(flight_schedule_id: flight_schedule, passenger_count: 1) %></td>
        <td><%= link_to 'Report', flight_schedule_path(flight_schedule) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New Flight Schedule', new_flight_schedule_path %>

app/views/flight_schedules/new.html.erb
<h1>New Flight Schedule</h1>

<%= render 'form', flight_schedule: @flight_schedule %>

<%= link_to 'Back', flight_schedules_path %>

app/views/flight_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight:</strong>
  <%= @flight_schedule.flight.name %> - <%= @flight_schedule.flight.code %>
</p>

<p>
  <strong>Departure airport:</strong>
  <%= @flight_schedule.departure_airport.city %>
</p>

<p>
  <strong>Destination airport:</strong>
  <%= @flight_schedule.destination_airport.city %>
</p>

<p>
  <strong>Departure Date:</strong>
  <%= @flight_schedule.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flight_schedule.price %>
</p>

<p>
  <strong>Number of confirmed seat:</strong>
  <%= @flight_schedule.seat_booked %>
</p>

<p>
  <strong>Number of Total seat:</strong>
  <%= @flight_schedule.flight.no_of_seat %>
</p>

<p>
  <strong>Number of Total Men Passenger:</strong>
  <%= @total_men_passenger %>
</p>

<p>
  <strong>Number of Total Women Passenger:</strong>
  <%= @total_women_passenger %>
</p>

<%= link_to 'Edit', edit_flight_schedule_path(@flight_schedule) %> |
<%= link_to 'Back', flight_schedules_path %>