config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :airports
  resources :passenger_details
  resources :bookings
  resources :flight_schedules
  resources :flights
  get "/cancle_booking/:id" => "bookings#cancle_booking", :via => :post, :as => :cancle_booking

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
	has_many :flight_schedules, dependent: :destroy
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:name, :code, :no_of_seat)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :no_of_seat %>
    <%= form.text_field :no_of_seat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(url: "flight_schedules", html: {class: "d-flex"}, method: :get) do |f| %>
  <%= f.collection_select :departure_airport_id, Airport.all, :id, :city, options ={prompt: "Please Select Departure", selected: params[:departure_airport_id]}, {class: "form-select form-select-lg mb-3"} %>
  <%= f.collection_select :destination_airport_id, Airport.all, :id, :city, options ={prompt: "Please Select Destination", selected: params[:destination_airport_id]}, {class: "form-select form-select-lg mb-3"} %>
  <%= f.text_field :departure_date, class: "input-group-text mb-3", placeholder: "Enter Departure Date dd/mm/yyy", value: params[:departure_date] %>
  <%= f.submit 'Search', class: "btn btn-outline-success mb-3"%>
<% end %>

<h1>Flights</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>No of seat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %></td>
        <td><%= flight.code %></td>
        <td><%= flight.no_of_seat %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><% link_to 'Edit', edit_flight_path(flight) %></td>
        <td><% link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flight.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @flight.code %>
</p>

<p>
  <strong>No of seat:</strong>
  <%= @flight.no_of_seat %>
</p>

<% link_to 'Edit', edit_flight_path(@flight) %>
<%= link_to 'Back', flights_path %>